### PR TITLE
Use test/REQUIRE for test dependencies LinearOperators and MatrixDepot

### PR DESCRIPTION
**Pull request by tkelman**
rather than adding them manually on Travis

### CODE REVIEW

**Comment by tkelman** [comment]
CI failures look like a timeout and some tolerances that are too tight.

**Comment by lruthotto** [comment]
thanks, tony.  this has been on my todo list for a while. I updated my old pull request for the new version number  here: https://github.com/JuliaLang/METADATA.jl/pull/5351 Can we merge this now?

**Comment by tkelman** [comment]
Yes, if you replace the 0.2.0 git tag here with the corresponding sha https://github.com/lruthotto/KrylovMethods.jl/releases

**Comment by lruthotto** [comment]
OK, this should be done.

**Pull request merged**
